services:
  DiscoveryService:
    image: discovery:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - discovery-network
    container_name: discovery
    environment:
      - EUREKA_INSTANCE_INSTANCEID=discovery
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - EUREKA_INSTANCE_NONSECUREPORT=8761

  configService:
    image: config-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - discovery-network
    container_name: config-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/

  employeeservice:
    image: employee:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    networks:
      - discovery-network
    container_name: employee-service
    depends_on:
      - DiscoveryService
      - configService
      # - h2database
    environment:
      - spring.cloud.config.uri=http://configService:8888
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      # - spring.datasource.url=jdbc:h2:tcp://h2database:8000/~/data/eployeeDB
      # - spring.datasource.driverClassName=org.h2.Driver
      # - spring.datasource.username=sa
      # - spring.datasource.password=
      # - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      # - spring.h2.console.enabled=true
      # - spring.jpa.hibernate.ddl-auto=update
      - SPRING_PROFILES_ACTIVE=dev  # Chỉ định profile active là 'dev' để load file application.properties

    

  bookService:  
    image: books:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    networks:
      - discovery-network
    container_name: book-service
    depends_on:
      - DiscoveryService
      - configService
      # - h2database
    environment:
      - spring.cloud.config.uri=http://configService:8888
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      # - spring.datasource.url=jdbc:h2:tcp://h2database:8000/~/data/bookDB
      # - spring.datasource.driverClassName=org.h2.Driver
      # - spring.datasource.username=sa
      # - spring.datasource.password=
      # - spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
      # - spring.h2.console.enabled=true
      # - spring.jpa.hibernate.ddl-auto=update
      - SPRING_PROFILES_ACTIVE=dev  # Chỉ định profile active là 'dev' để load file application.properties

  apigateway:
    image: apigateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - discovery-network
    container_name: apigateway-service
    depends_on:
      - DiscoveryService
      - configService
      - employeeservice
      - bookService
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/

  # h2database:
  #   image: oscarfonts/h2:latest
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - discovery-network
  #   container_name: h2-database
  #   environment:
  #     - H2_OPTIONS=-ifNotExists
  #   volumes:
  #     - ./data:/h2-data
  #   command: ["java", "-cp", "h2-1.4.200.jar", "org.h2.tools.Server", "-tcp", "-tcpAllowOthers", "-web", "-webAllowOthers", "-ifNotExists", "-tcpPort", "8000", "-baseDir", "/h2-data"]



networks:
  discovery-network:
    driver: bridge
